[package]
name = "photothing_api"
version = "0.1.0"
authors = ["Nathan Merritt <gnm@the-merritts.net>"]

[dependencies]
futures = "0.1.17"
rocket = "0.3.14"
rocket_codegen = "0.3.14"
rocket_contrib = "0.3.14"
rocket_cors = "0.2.3"
rusoto_core = { git = "https://github.com/rusoto/rusoto", rev = "e0790ca" }
rusoto_s3 = { git = "https://github.com/rusoto/rusoto", rev = "e0790ca" }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

[dev-dependencies]
reqwest = "0.8.6"
